### ISSUE TITLE
Replacing "Featured Stores" link in the navigation menu to "All Stores"

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#139] opened 2018-05-10 14:13 UTC
This is a two prong issue.

1. We need a page built called "all-stores" that has all the stores on one page and are sortable three different ways.  "A to Z", "Z to A", and by "Points Offered - High to Low"

It will emulate (as much as it pains me to reference this site 'cause I think it is terrible), https://www.totalrewardsmarketplace.com/allMerchants#anchor-h

Notice the anchor to each letter so someone can easily jump to a store that starts with that letter

2. Replace the "Featured Stores" link in the navigation menu to "All Stores" and have the drop down menu include the sorting choices, BUT is it possible to have the words "All Stores" in the menu both initiate the drop down menu AND act as a link to the all-store page itself.

Then on the all-store page itself, the user would have the same sorting abilities on the page as they would from the menu options in the drop down under All Stores in the main navigation, PLUS the ability to click on a letter to take them to all the stores that start with that letter (or number).

**Comment by robgpeak** [comment] 2018-05-18 14:29
What does the tag "ready" mean?

**Comment by ChrisASearles** [comment] 2018-05-30 18:48
Ok, so here goes on this one ...

First, @cgladue I updated some core stuff while I was working on this. Since Bower has been deprecated, I migrated all the Bower stuff to NPM and I updated all of the core libraries. I've tested just about everything I could and it was only a minor version update so breaking changes should have been limited (and we're not doing a ton with the library) but it still wouldn't hurt for another set of eyes on it to make sure I didn't miss anything.

I also added two methods to the DAL in the AdvertiserDAL class to support the loading of all active advertisers for each partner (more on this later). Finally, I added a constructor overload to CompLinksWeb.Models.Advertisers.Advertiser that takes an Advertiser object that might save you a few hundred lines of code in that file if you want to take advantage of it.

On to the "All Stores" feature ...

@robgpeak originally I was concerned about how long this page would take to load so I built it to load all of the data asynchronously, one letter at a time, so users could begin to browse while the rest of the data loaded in the background. Unfortunately, that version is painfully slow. I also threw together a version that loads it all at once which is also painfully slow (a quick test had them almost identical).

I wanted to commit what I have for now to open a discussion about how best to accomplish this. I'm not connected enough to the database or the hosting environment to be all that helpful so I wanted to see if @cgladue had any suggestions. My initial thought is that a stored procedure could go a long way. Any chance you can put together a proc to replace the LINQ queries I wrote in the DAL so we can see what the performance improvement looks like?

For now, the new pages are up at "/Stores/All" and "/Stores/AllPaged".

**Comment by robgpeak** [comment] 2018-05-30 18:55
@ChrisASearles I am not sure how they're doing it, but this page loads in about a second https://www.totalrewardsmarketplace.com/allMerchants  I just went from an incognito window so it is not coming out of cache.

**Comment by cgladue** [comment] 2018-05-31 02:38
i tried it on my pc and the method never returned, i commented out your constructor and put it back the way i was doing it and now it loads a little slow, but loads...

![image](https://user-images.githubusercontent.com/7914133/40758188-1290be00-645a-11e8-88c8-38c7b9a07c26.png)


am i reading this right that onesignal is taking 5 seconds to load ?

**Comment by cgladue** [comment] 2018-05-31 02:40
https://xclub.complinks.co/stores/all

**Comment by cgladue** [comment] 2018-05-31 02:47
@robgpeak also there are some really large images for these advertisers, maybe re-upload smaller ones ?  most are over half a megabyte:

![image](https://user-images.githubusercontent.com/7914133/40758436-51cba80e-645b-11e8-8243-e12ae01b1ce4.png)


![image](https://user-images.githubusercontent.com/7914133/40758454-64fd1ff2-645b-11e8-8227-4724870b57de.png)

**Comment by robgpeak** [comment] 2018-05-31 03:05
@cgladue try them now

**Comment by robgpeak** [comment] 2018-05-31 03:07
any others?  None of them should really be more than 50kb, and that is still pretty big relatively speaking.

**Comment by cgladue** [comment] 2018-05-31 03:11
@robgpeak looks good now just those two it seems, but its still a little slow, i think part of the issue is the fact there is 800+ images loading before the page loads... @ChrisASearles is there any way to load the images async ?

![image](https://user-images.githubusercontent.com/7914133/40759171-d5faf816-645e-11e8-8de8-34a7c80fea15.png)

**Comment by robgpeak** [comment] 2018-05-31 03:14
@cgladue I mentioned this earlier in the thread, but if you go to https://www.totalrewardsmarketplace.com/allMerchants it seems to load just as many advertisers in 1/4 the time.  Maybe you can see what they are doing?

**Comment by cgladue** [comment] 2018-05-31 03:14
@ChrisASearles perhaps this? https://www.npmjs.com/package/ng-async-img

**Comment by ChrisASearles** [comment] 2018-05-31 12:33
It's actually about 10,000 times faster on the production site, must be the connection from my machine to the DB when I'm testing.

**Comment by ChrisASearles** [comment] 2018-05-31 12:34
Async page is here: https://xclub.complinks.co/stores/allpaged 

@cgladue the constructor was slowing it down for you or not working at all?

**Comment by ChrisASearles** [comment] 2018-05-31 12:40
Knowing that it's at least significantly faster when it's live, I can play with the async version and get it up to speed. Stay tuned ...

**Comment by cgladue** [comment] 2018-05-31 13:04
I let it run for a long time.  And never returned.

**Comment by ChrisASearles** [comment] 2018-05-31 16:10
@cgladue I just pushed up a new version of this, can you push that up and let me know when it's up there so I can see what it looks like loading this way in production.

Also, the async page is still using that constructor I built and seems to be loading fine for me (as is this version), there shouldn't be anything there that would cause an issue. The one thing it is missing, however, is the point text. I'm not quite sure how that's being built as it looks like it may be based on the category(?) but if you could update it to bring the point text down so I can get that text onto this page I'd appreciate it!

**Comment by ChrisASearles** [comment] 2018-06-15 19:18
This is pretty much good to go but I still haven't heard anything back on the point text. I also would need an integer value passed down representing the number of points / dollar spent to accomplish the other sort functionality @robgpeak is looking for.

@robgpeak When sorting by points, what do you envision happening with the alphabetical listing? would it be sorted by points for each letter or are we looking at some way to pull that functionality out completely in that event?

**Comment by ChrisASearles** [comment] 2018-06-15 20:06
@cgladue yes, and the point text.

**Comment by robgpeak** [comment] 2018-06-18 19:09
@ChrisASearles I know you and Chad are working on the sorting by points, but the "Back to Top" link on the page is being covered by the Intercom widget... (which only shows up when someone is authenticated)

<img width="393" alt="screen shot 2018-06-18 at 3 08 04 pm" src="https://user-images.githubusercontent.com/28393235/41556614-4dd46a3a-7309-11e8-902d-83ad0b47b96a.png">

Can you please offset it from the right margin enough so that it is visible on both the desktop and the mobile version of the site?

**Comment by robgpeak** [comment] 2018-06-27 23:52
@ChrisASearles  where are we on my last post in this issue?

And my first post....?  Replace the "Featured Stores" link in the navigation menu to "All Stores" and have the drop down menu include the sorting choices, BUT is it possible to have the words "All Stores" in the menu both initiate the drop down menu AND act as a link to the all-store page itself.

**Comment by ChrisASearles** [comment] 2018-07-12 18:33
@robgpeak sorry, this and a couple others are getting stuck b/c they're never getting assigned back to me. I'll get into this, can you make sure to reassign anything to me that needs my attention?

**Comment by robgpeak** [comment] 2018-07-12 22:30
@ChrisASearles without assigning it back to you, what I am looking for in the dropdown would have the same functionality as the current "Featured Stores" link in the navigation menu.  Meaning when you click on Featured Stores, it initiates a drop down now...

<img width="639" alt="screen shot 2018-07-12 at 6 21 31 pm" src="https://user-images.githubusercontent.com/28393235/42662857-280ca424-8601-11e8-98f9-70492872c845.png">

I would like the same functionality but it would read like this...

<img width="634" alt="screen shot 2018-07-12 at 6 30 30 pm" src="https://user-images.githubusercontent.com/28393235/42662901-57c1db62-8601-11e8-900a-a5c8f40fff14.png">


Then when the user choses either one of those choices, the all page would be sorted accordingly when they get there.

The other thing was the "Back to the top" arrow showing up under the Intercom widget.  It needs to be moved over to the left so it is visible.

**Comment by ChrisASearles** [comment] 2018-07-13 11:46
Ahhh, sort options in the dropdown, got it. Shouldn't be a problem. And yes, aware of the issue with that, will get all that done as soon as we can get back in to work on them all together.

**Comment by cgladue** [comment] 2018-07-14 02:13
@ChrisASearles the point value / dollar is already available the property is called "comissionTo"

as is the point text, but since every partner could have a different share rate and therefore different points/$ for the same advertiser you need to get the advertisers and also pass in the partnerId so i can calculate the proper sharerate, there are a few other constructors one of which accepts partnerId and shareRate  what controller and view is this data going to ?

**Comment by robgpeak** [comment] 2018-07-18 17:36
@ChrisASearles I just wanted to find out where we were on these issues?

1. Inclusion of ponts/$
2. The moving of the "back to top" button based on my June 18th comment
3. Adding it to the main Nav Menu (of course this is after 1 & 2 are complete)

**Comment by ChrisASearles** [comment] 2018-07-18 20:33
@cgladue the view is Views/Stores/All.cshtml

Please let me know once the text is being passed down and @robgpeak we'll wrap up those items

**Comment by cgladue** [comment] 2018-07-19 02:56
@robgpeak @ChrisASearles all set PointText contains the point verbiage and ppd contains the starting Percentage and ppdTo contains the ending percentage range.

**Comment by robgpeak** [comment] 2018-07-20 17:54
@ChrisASearles I see the points/$ spent in the listings, which is good, now we just need the other items buttoned up.

**Comment by robgpeak** [comment] 2018-07-25 12:59
Hi @ChrisASearles I wanted to find out where we were on this?

**Comment by ChrisASearles** [comment] 2018-07-25 14:37
@robgpeak working on the point sorting and the changes to the nav to alter the default sort as we speak

**Comment by ChrisASearles** [comment] 2018-07-25 19:56
@cgladue I committed a version of this that's working just without the sort by points option that I'm having a little trouble with. That version should be good to go and I'll update this as soon as I get that last option working.

**Comment by ChrisASearles** [comment] 2018-07-25 21:33
Points sort is working, working on one other issue but the version that's there should be good to go.

**Comment by cgladue** [comment] 2018-07-26 02:50
should be set now rob and chris

just deployed



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment] 2018-07-26 11:54
Chris, I know you said you are still working in some things, but I see some concerning issues.

1. The page still does take WAY to long to load compared to the total Rewards Marketplace site.  How is it that their POS site can load faster than ours?

2. Once you navigate within the page, e.g. click in a letter to jump to it, or sort by points, and then use the Top button, nothing else works after that.  Meaning the main navigation hamburger menu, the head and shoulders icon, search etc.  Of course I am on my phone. Please try it incognito

3. The link to all stores in the navigation menu should replace the featured store link, but it can use the same "little store" looking icon.

**Comment by robgpeak** [comment] 2018-07-26 13:13
@ChrisASearles In addition to my last post on this thread an hour ago, here is a screen cast I made to show you. https://www.dropbox.com/s/nzwt3q13fg4y2fv/20180726_082316.mp4?dl=0

**Closed** 2019-01-11 13:12 UTC
Labels: 2 - Working <= 5
