### ISSUE TITLE
Sam's Club transactions not showing up.

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#173] opened 2018-06-20 21:47 UTC
@cgladue For some reason Sam's Club purchases are not showing up in our back end.

This guy https://shop.complinks.co/dashboard/users/view?id=100224 made a bunch of trips that ended in sales that paid commissions, but none of them are showing up in our back end.

I ran this report:
<img width="1015" alt="screen shot 2018-06-20 at 5 43 42 pm" src="https://user-images.githubusercontent.com/28393235/41686325-a2ed9420-74b1-11e8-8f6c-4dfc84331394.png">

and the results are here: 

[Individual-Item-Report4-1--6-20.csv.zip](https://github.com/robgpeak/CompLinks-xclub/files/2121232/Individual-Item-Report4-1--6-20.csv.zip)

**Comment by cgladue** [comment] 2018-06-21 13:32
i know what the issue is .. its the same issue i adressed with linkshare months ago and they just dont get it ... 

in the API some of the advertisers were reporting their sales as "batch" and also as "realtime" but the transaction IDs for the two were different, order #s were different ... nothing that i can use to tr to choose only one of the two to post without double posting the comissions... they said their advertisers can choose to report realtime or batch but not both, i told them they were showing up as both and causing issues, if it was 1 or the other then thats fine i can work with that but not both and with different IDs to boot!

so i said fine, we will just post the batch transactions and not realtime since not everyone used realtime but seemed that everyone was showing up as batch.

well with sams club it appears they are only showing up as realtime and not batch .. so they were skipped.

so i think this is what i will have to do, add a field to the advertiser record that is either batch or realtime, and we will have to manually set it to whatever transaction type we want to post.  i asked and theres no way to get the method of reporting through an API from LS, 

i dont see any other possible way, god i hate LS

**Comment by robgpeak** [comment] 2018-06-21 13:38
That sucks.  I thinks it's ebates' plan to make it as difficult as possible for other competitors... Bastards!

**Comment by robgpeak** [comment] 2018-06-21 13:39
And I'm assuming the only way to know to set it from hatch to real time is for it to happen like this again and then we would know?

**Comment by cgladue** [comment] 2018-06-21 13:40
yea i guess, i think they may have said theres a report that can be ran that shows the reporting method, let me check my email

**Comment by cgladue** [comment] 2018-06-21 13:43
Hello Chad,

Hope this email finds you well!

I apologize for the inconvenience caused as you are getting batch transactions in events API. Please be informed that different advertisers have opted for different tracking methods, i.e real-time and batch. That is the reason that you are currently viewing the transactions getting reported after few days. 

Further, as you have stated that SKUs or Order IDs does not match between real-time and batch method, I would like to inform you that the advertiser who has opted for batch method reports the transactions after few days and hence, you view new transactions for the same day after several days has passed. You can view the advertiser opted for different transaction methods by following these steps on your dashboard:

1. Log in to your publisher dashboard.
2. Go to Programs > My Advertiser in your dashboard.
3. Select your preferred advertiser. Click on the name or logo of the advertiser.
4. You will be redirected to the Advertiser Information page.
5. Go to Tracking > Tracking Reporting option.
6. You can find your advertiser's tracking method here.

**Comment by cgladue** [comment] 2018-06-21 13:44
not even a report, just a field on the individual advertiser :\

**Comment by robgpeak** [comment] 2018-06-21 13:58
That is unbelievably dumb.  Let me know what I can do to help.

**Comment by cgladue** [comment] 2018-06-21 14:35
i have added Reporting Method to the Advertiser edit modal.  now working on the commission posting program to use that value.

**Comment by cgladue** [comment] 2018-06-21 14:36
![image](https://user-images.githubusercontent.com/7914133/41725877-ec2d7e92-753e-11e8-8817-718f5131515b.png)

**Comment by cgladue** [comment] 2018-06-21 15:23
@robgpeak this should be fixed now (for sams club at least)

**Closed** 2018-06-22 15:45 UTC
Labels: 3 - Review
