### ISSUE TITLE
tracking for Home Depot

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#86] opened 2018-04-03 17:20 UTC
@cgladue I reached out on Linkedin to the guy who runs the affiliate program for Home Depot and I asked him why we are not receiving the standard commission and he wrote back with... below.  Can you please look into it and see what he might be talking about?  I am going to forward the original email we got from home depot again.

![uploads/31fac324-0e7b-4e7c-b27b-6f4fb740da9c/Screen Shot 2018-04-03 at 1.15.57 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F31fac324-0e7b-4e7c-b27b-6f4fb740da9c%2FScreen+Shot+2018-04-03+at+1.15.57+PM.png)

**Comment by robgpeak** [comment] 2018-04-06 19:42
I did some searching and came up with this I thought might help shed some light...  https://www.fmtc.co/cj-impression-tracking-home-depot/

**Comment by robgpeak** [comment] 2018-04-06 19:54
I'm not sure if this would work, but in reading what they are seemingly looking for, it maybe if we had this pixel in the image below (which is attributed to their home page), incorporated somehow into the Show Now buttons on our site specifically for Home Depot, that might work...

<img width="918" alt="screen shot 2018-04-06 at 3 50 10 pm" src="https://user-images.githubusercontent.com/28393235/38441437-b8eccbb8-39b2-11e8-997a-cf3631f0fb11.png">

**Comment by cgladue** [comment] 2018-04-06 20:00
hmm, that may be what they want ... ill see if i can locate that link code
in the links we currently have downloaded for them.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment] 2018-04-06 20:06
I went to a competitor who is actively promoting home depot and getting 5% commission to see if they were tracking the impressions, but I did not really know what I was looking for in the inspect screen...

<img width="1267" alt="screen shot 2018-04-06 at 4 04 37 pm" src="https://user-images.githubusercontent.com/28393235/38441951-74162c4e-39b4-11e8-9d5b-710aada7e4fa.png">

**Comment by cgladue** [comment] 2018-04-21 03:28
@ChrisASearles @robgpeak 

i found where the link tracking code is being returned by the API... here is an example of the HTML: 

`<a href="http://www.dpbolvw.net/click-8235261-13196600-1518120667000">Up to 40% off Furniture at The Home Depot!</a><img src="http://www.lduhtrp.net/image-8235261-13196600-1518120667000" width="1" height="1" border="0"/>`

@ChrisASearles how can this work with the ng-button elements we use for our links ?

**Comment by cgladue** [comment] 2018-04-21 03:29
@ChrisASearles this would be just for home depot...

**Comment by ChrisASearles** [comment] 2018-04-23 15:17
Hey @cgladue I'm not seeing this property in the objects being passed down anywhere, can you let me know what the field is so I can add it?

**Comment by cgladue** [comment] 2018-04-30 02:31
@ChrisASearles the property is on the Link record and its called "linkCodeHTML"

**Comment by ChrisASearles** [comment] 2018-05-02 20:58
This is committed. I didn't see the same field on the Advertiser class but there are a few locations where you can start a trip direct from the advertiser record. Let me know if we need to add something there.

**Comment by cgladue** [comment] 2018-05-02 20:59
ok, i will look at this ...

**Comment by robgpeak** [comment] 2018-05-18 15:51
@cgladue OK, well at least this flying monkey wrench was not thrown by me...

I just signed us up for the Home Depot affiliate program through IR and here is the link to see their ads so you can replicate the tracking code stuff that you did for CJ in order to be in compliance with their terms...  https://app.impact.com/secure/mediapartner/ads/searchAdsDirectoryMP.ihtml?ecid=TjKaZExwA0-yJuFYvPKRr44cTborz6ES

Once this is done, let me know and I will have them adjust the commission to be more than 0%

**Comment by cgladue** [comment] 2018-05-18 16:15
have you been accepted into the campaign on IR yet ?  i dont see any links
for Home Depot int he API nor do i see them listedunder active campaigns ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment] 2018-05-18 16:18
No, and for some stupid reason, IR created another account even though I indicated I was an existing account holder.  I just sent them an email to have them clarify or fix it.  stay tuned...

**Comment by cgladue** [comment] 2018-05-22 18:22
have you done this portion? :

> Click on the “Ads” dropdown
Under the “Actions” column for the ads you want to promote, click on link “Get Code”
Click on link “Customize Code”
Make sure “Enable Viewable Impressions” is checked”

**Comment by robgpeak** [comment] 2018-05-22 18:39
Every one that I went into had the “Enable Viewable Impressions” checked.  So it seems like it comes that way by default.

**Comment by cgladue** [comment] 2018-05-22 18:56
ok, i believe its already working like it was on CJ.. can you disable the CJ advertiser and enable the IR one and see ?

**Comment by robgpeak** [comment] 2018-05-22 19:03
done

**Comment by cgladue** [comment] 2018-05-22 19:58
ok, i just confirmed it looks like the tracking is actually the same as what was done to get the CJ one working...

you can request they take a look now and they should enable higher comission

**Comment by robgpeak** [comment] 2018-05-22 19:59
👍

**Closed** 2018-05-22 20:32 UTC
Labels: 3 - Review
